#!/bin/bash

if ["$1" === 'server']; then
    yuidoc .
    cd server
    clear
    echo "Invoking server..."
    node entry.js
fi

if ["$1" === "client"]; then
    yuidoc .
    cd client
    clear
    yarn start
fi